# Generated by Django 4.2.16 on 2024-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='mark_done',
            field=models.BooleanField(default=False, verbose_name='mark'),
        ),
    ]
